services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - pcg-network

  fcg_usersapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: fcg_usersapi:latest
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PCGPROJ;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - pcg-network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  pcg-network:
    external: true
